name: Checkout Submodule

description: name: Checkout private enterprise submodule

inputs:
  submodule_branch:
    description: 'Submodule branch to checkout to'
    required: true

runs:
  using: composite

  steps:
    - name: Checkout submodule
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUBMODULES_TOKEN }}
        repository: novuhq/packages-enterprise
        path: enterprise/packages
        ref: ${{ inputs.submodule_branch }}
