version: "3"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    logging:
      driver: "none"
  mongodb:
    image: mongo
    container_name: mongodb
    logging:
      driver: "none"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
volumes:
  mongodb: ~
